### ISSUE TITLE
Changing content data (file path & file name) need to change other columns as well

### ISSUE THREAD

**Issue by ben-hearn-sb** [dylanljones/pyrekordbox#104]
**Describe the bug**
When changing the "FilePath" column in the "update_content_path" function, the code should also be changing the "OrgFolderPath" coilumn **if** the column has a value and if it matches with the FilePath column

Inside the "update_content_filename" function, you are only changing the FilePath column by calling the aforementioned function and should also be changing the FileNameL column.

Functions present at lines: 1825 & 1900 of the database.py file

Great work all around!

**Comment by dylanljones** [comment]
Thanks again for the help:)
