### ISSUE TITLE
PSSI tag beat field not being parsed correctly

### ISSUE THREAD

**Issue by worldveil** [dylanljones/pyrekordbox#108]
## Describe the bug

Inside each parsed `PSSI` struct, the `SongStructureEntry`'s `beat` field is not parsed properly. The numbers are far too large. I am not sure if this is an endianness issue, or an offset problem.

I can share the .EXT file if you like as well if you'd like to reproduce.

## To Reproduce

```python
import os
from pyrekordbox.anlz import AnlzFile

path = os.path.expanduser("~/Desktop/ANLZ0000.EXT")
anlz = AnlzFile.parse_file(path)
for song_structure_struct in anlz.get('PSSI').entries:
    print(song_structure_struct.beat)
```

The resulting output is:
```
62718
63756
63933
60541
65349
1305
62932
62903
60767
61776
56381
```

**Expected behavior**
The output should be much smaller numbers, and of course, they would also have to be monotonically increasing. In this case, I checked the exact numbers with the [online parser tool](https://ide.kaitai.io/#), and they should be:

```
1
9
73
137
169
233
265
329
393
425
457
```

and here's a screenshot of the first two entries:

<img width="550" alt="Screenshot 2023-12-10 at 11 43 02 PM" src="https://github.com/dylanljones/pyrekordbox/assets/1045250/a68cd315-69e8-4d55-8008-5029838389d4">

I can also verify by checking in rekordbox itself, and indeed, the first two entries should start at 1 and 9:

<img width="141" alt="Screenshot 2023-12-10 at 11 42 45 PM" src="https://github.com/dylanljones/pyrekordbox/assets/1045250/7ffe83ac-84be-440a-96d1-3a6190fce74d">

so clearly we're either not: 1) parsing the right binary chunk of data, or 2) not using the correct interpretation of that chunk (ie: endianness, type, etc). what do you think it could be? I'm more than happy to help dig in, but just wanted to document this in case you had some suggestions.

**Environment**
- Pyrekordbox version: `master` (`2f13a93c9d22b709902b05394b64667491d7dbd0`)
- Rekordbox version: `6.6.9`

**Comment by worldveil** [comment]
My understanding is that the tag parsing for PSSI structs happens [here](https://github.com/dylanljones/pyrekordbox/blob/master/pyrekordbox/anlz/file.py#L136). This dispatches to [`SongStructureEntry`](https://github.com/dylanljones/pyrekordbox/blob/master/pyrekordbox/anlz/structs.py#L200) so it appears that the issue lies somewhere around here.

**Comment by dylanljones** [comment]
Thanks for catching this, there was a bug where the parser decides if the PSSI tag is garbled or not:

https://github.com/dylanljones/pyrekordbox/blob/2f13a93c9d22b709902b05394b64667491d7dbd0/pyrekordbox/anlz/file.py#L118C1-L121C57

The `bank` field can also have a value of 0, which i missed! Therefore the PSSI tag in your case is masked with the XOR mask, even though it shouldn't.

**Comment by dylanljones** [comment]
Should work now, can you try the latest version?

**Comment by worldveil** [comment]
yes, it works, thank you!
