### ISSUE TITLE
Is it currently possible to create/import new tracks (DjmdContent)?

### ISSUE THREAD

**Issue by cvdub** [dylanljones/pyrekordbox#118]
I didn't see anything in the API reference. Has anyone tried this yet? Is it possible to just create all the relevant `djmd` models?

**Comment by nzoschke** [comment]
Same question here... From poking at the database I suspect its tricky.

Importing a track through the UI sets a lot of initial `djmdContent` fields.

```
SELECT * FROM djmdContent ORDER BY updated_at DESC LIMIT 1

157547285|/path/to/example.flac|example.flac||Example|585525948|1313609794||0|432|4|0|0||5|0|2011||1661880977||0|2025-01-30|0|0||632586089|157547285|||40538903|0|||0||0||2025-01-29|14|||on|on||||||DEY470906483|0|0|0.0|0|0|0||||||null|34997065|d8b55d49-4274-43d5-a982-a06dc6ac7f40|||||||542fa459-d20d-4dca-8fa6-a85f0566c3f1|0|0|0|0||143674|2025-01-30 20:50:14.823 +00:00|2025-01-30 20:50:14.823 +00:00
```

After analysis even more of the fields are automatically filled in.

Perhaps there's a way to create this record and related records programmatically, but I'm guessing it'd take reverse engineering what the right INSERT commands are for djmdContent and relations like djmdArtist plus some generated numbers etc.

**Comment by cvdub** [comment]
pyrekordbox does support importing tracks as of PR #121. See [this section of the docs](https://pyrekordbox.readthedocs.io/en/latest/tutorial/db6.html#tracks) for a summary of how it works.
