### ISSUE TITLE
Accessors for reverse realtionships

### ISSUE THREAD

**Issue by jvacek** [dylanljones/pyrekordbox#37]
It would be nice if the Playlist ↔︎ song through table would provide the reverse accessors. This way you could access the songs from a playlist directly and not using the filter. https://docs.sqlalchemy.org/en/14/orm/relationship_api.html#sqlalchemy.orm.relationship.params.back_populates

**Comment by dylanljones** [comment]
Hey,
thank you for your suggestion! To be honest the v6 Database handler is in the very early stages, but i plan to implement more accessors and a better API in general. Any suggestions/ideas are welcome!:)

**Comment by dylanljones** [comment]
thanks again for the suggestion!
