### ISSUE TITLE
Add docs link as link of repo

### ISSUE THREAD

**Issue by mrzmyr** [dylanljones/pyrekordbox#39]
Hi @dylanljones, why not adding https://pyrekordbox.readthedocs.io/en/stable/ as the repo link? 
![CleanShot 2022-09-21 at 10 41 32](https://user-images.githubusercontent.com/746429/191458015-355d2c9e-8570-4a69-b5d3-ce294683858e.png)

**Comment by dylanljones** [comment]
Will do that as soon as the project is a bit more advanced and the documentation is complete!
