### ISSUE TITLE
Question: How to access Models?

### ISSUE THREAD

**Issue by mrzmyr** [dylanljones/pyrekordbox#40]
Hi @dylanljones, 

How would I access the models (`DjmdHistory`) to do something like `db.get_history().order_by(DjmdHistory.DateCreated.desc())`?

Currently, I initialize the models on my own using your template from [tables.py](https://github.com/dylanljones/pyrekordbox/blob/master/pyrekordbox/db6/tables.py).

I could not get it working by `from pyrekordbox import Rekordbox6Database, DjmdHistory`

**Comment by dylanljones** [comment]
Hey @mrzmyr,

sorry for the late reply. I am not sure if I understand the question correctly, but you can access the `DjmdHistory` table as you stated! For importing the actual object, use
````python
from pyrekordbox.db6 import DjmdHistory
````
The results from the query can then be iterated over:
````python
db = Rekordbox6Database()
for item in db.get_history().order_by(DjmdHistory.DateCreated):
    print(item.Name)
````
Hope that helps!
