### ISSUE TITLE
It seems this project found a way to get the DB key automatically.

### ISSUE THREAD

**Issue by fabiomarastoni** [dylanljones/pyrekordbox#77]
Hi, I love this initiative but struggling to make your code working due to the DB key.

It seems this other guys found a way. I'm not super technical so I can't figure it out.

https://github.com/dvcrn/go-rekordbox
https://github.com/dvcrn/go-rekordbox/blob/8be6191ba198/cmd/getencryptionkey/main.go

**Comment by EvzenP** [comment]
That project just hardcodes a DB key taken from another project:
https://github.com/mganss/CueGen/blob/19878e6eb3f586dee0eb3eb4f2ce3ef18309de9d/CueGen/Generator.cs#L31

Apparently, the key is still valid in Rekordbox 6.7.3 - works great with [DB Browser for SQLite (Cipher)](https://sqlitebrowser.org/)

**Comment by fabiomarastoni** [comment]
Cool! Thanks for your reply!

**Comment by dylanljones** [comment]
Hey, thank you for your interest in the project!
Yes, the key is still the same, so if you have an old Rekordbox installation you can just print out the key and pass it to the DB handler manually;)
