### ISSUE TITLE
Import tracks from XML in to rekordbox 5 collection

### ISSUE THREAD

**Issue by luke-1993** [dylanljones/pyrekordbox#80]
First of all, thanks a lot for this package! This is not a feature request for pyrekordbox but just wanted to ask if anyone knew of a way to achive the following.

I've created an app that uses this package to make a rekordbox xml from tracks on disk. I then import the created rekordbox xml in to rekordbox. I'd then like to import the tracks and playlist structure from the XML in to rekordbox's collection. As far as I know, rekordbox only has a export to xml option, not an import from xml one. Any idea how I can do this?

In the attached image I want to import the highlighted 'rekordbox xml' in to the collection. 

<img width="1512" alt="image" src="https://github.com/dylanljones/pyrekordbox/assets/14069946/b1fbefc2-7108-4c31-aac0-84694d7d552c">

**Comment by JOJ0** [comment]
Just wild guessing because afk, but does right clicking on playlists foo and bar offer anything helpful for importing?

**Comment by luke-1993** [comment]
I did try that but it didn't work. Realise now that was because the file paths in the XML were incorrect. Fixed that and it now works. Thanks. Closing this issue.
