### ISSUE TITLE
How to overwrite the artwork of tracks in the RBv6 database?

### ISSUE THREAD

**Issue by jcardonne** [dylanljones/pyrekordbox#83]
**Is your feature request related to a problem? Please describe.**
I would like to overwrite the image path of tracks.

**Describe the solution you'd like**
A method to overwrite the X metadata of an Y song by it's id

**Additional context**
I only found that it's possible to read data but not write on

**Comment by dylanljones** [comment]
Hey,

as you pointed out, *adding* new rows to the database is not possible until now. 
In principle it is possible, but I’ve noticed some weird behavior that I don’t yet fully understand. If you update the database and open Rekordbox, the changes appear as expected. However, after closing and reopening Rekordbox, most of the time the added items don’t show up anymore, even though they are still in the master.db file. 
I am still trying to figure out what causes this, but I’m certain it can be done somehow. But that probably will take some time and a lot of testing, since I don’t want to publish anything that could mess up the library of people.

In your case, however, I think it should be possible, since the `ImagePath` is just a regular text field, so changing the value should not cause any issues. There is a `ImageFile` table, but at least in my case it is empty. The only thing to figure out is how Rekordbox decides where to store the image (somewhere in `/shared/Artwork/<three letters>/<UUID>`. I'll do some testing to see if it works to just place the new image in the same directory.

**Comment by dylanljones** [comment]
I did some testing, and it seems to work to replace the three artwork images. However, i still don't know how Rekordbox decides which parent folder to use for the artworks, specifically the name before the UUID directory. As stated above, it is a three character directory, for example:
````
 b16, 859, 4d1, ...
````
It seems the name is chosen randomly (not a part of the UUID or something else). Will have to look into that more.

If you only want to *update* the artwork of tracks that already had a different artwork, you can use the code snipped below. I will add the feature as soon as it is possible to add *new* artworks.

<details><summary>Code</summary>

````python
import os
from PIL import Image
import numpy as np
from skimage.transform import resize
from pyrekordbox import Rekordbox6Database


def pad_image(image: np.ndarray) -> np.ndarray:
    shape = image.shape
    size = max(shape)
    dw, dh = size - shape[1], size - shape[0]
    padw, padh = dw // 2, dh // 2
    padding = [(padh, dh - padh), (padw, dw - padw)]
    if len(shape) == 3:
        padding.append((0, 0))

    image_padded = np.pad(image, padding, mode="constant", constant_values=0)
    assert image_padded.shape[0] == image_padded.shape[1], "Image is not square"
    return image_padded


def rescale_image(data, size, anti_aliasing=False):
    if size[0] != size[1]:
        raise ValueError("Image size must be square")
    rescaled = resize(data, size, anti_aliasing=anti_aliasing, preserve_range=True)
    return rescaled.astype(data.dtype)


def save_artworks(db, content, src_file, anti_aliasing=True):
    # Read image data
    with open(src_file, "rb") as fp:
        image = np.array(Image.open(fp))

    # Pad image to square
    if image.shape[0] != image.shape[1]:
        image = pad_image(image)

    # Create medium image (240x240)
    image_m = rescale_image(image, (240, 240), anti_aliasing)
    # Create small image (80x80)
    image_s = rescale_image(image, (80, 80), anti_aliasing)

    # Save images to content folder
    img_relpath = os.path.dirname(os.path.normpath(content.ImagePath))
    img_relpath = img_relpath.lstrip(os.path.sep)
    img_root = os.path.join(db.share_directory, img_relpath)

    path = os.path.join(img_root, "artwork.jpg")
    with open(path, "wb") as fp:
        Image.fromarray(image).save(fp)

    path_m = os.path.join(img_root, "artwork_m.jpg")
    with open(path_m, "wb") as fp:
        Image.fromarray(image_m).save(fp)

    path_s = os.path.join(img_root, "artwork_s.jpg")
    with open(path_s, "wb") as fp:
        Image.fromarray(image_s).save(fp)


if __name__ == "__main__":
    db = Rekordbox6Database()
    src = <File path to new artwork>
    cid = <ContentID>

    content = db.get_content(ID=cid)
    save_artworks(db, content, src, anti_aliasing=True)
````

</details>

**Comment by GonyRosenman** [comment]
hey, thanks for your work!
i have a question - 
is it possible to edit the metadata of songs on Rekordbox programmatically? 
ideally i mean adding a new column that i could then see while mixing, or maybe also just modifying a tag/comment?
of course this is possible manually but i'm asking programatically.

**Comment by dylanljones** [comment]
Not sure what you mean by  manually/programmatically. 
For now, you can only change values of songs that don't link to other tables (for example Artist, Album, ...). Check the documentation of the `DjmdContent` table which fields store data directly: 
https://pyrekordbox.readthedocs.io/en/stable/formats/db6.html#djmdcontent

If you want to change the title of a track, for example, you can do so by assigning a new value to the attribute:

````python
from pyrekordbox import Rekordbox6Database

db = Rekordbox6Database()
content = db.get_content(ID=<id of song>)
content.Title = "New title"
db.commit()  # Save changes
````

Make sure to back up your Rekordbox library before making changes!

**Comment by jcardonne** [comment]
> Hey @jcardonne, does the script work for you?

Hey @dylanljones, late answer I know haha
I don't know why I can't get the share_directory from the DB
`AttributeError: 'Rekordbox6Database' object has no attribute 'share_directory'`

**Comment by dylanljones** [comment]
Hey @jcardonne, are you using the newest version? The attribute name changed recently.
`share_directory` should work:

https://github.com/dylanljones/pyrekordbox/blob/eb0bf179f987361f0a54514884a9576cc98dfd51/pyrekordbox/db6/database.py#L262-L266

**Comment by jcardonne** [comment]
I updated my packages and that worked, thanks!
