### ISSUE TITLE
Exporting decrypted database for manual browsing

### ISSUE THREAD

**Issue by gsuberland** [dylanljones/pyrekordbox#86]
Is there a way to load the encrypted database with a key, then export it as a plaintext database for manual browsing and inspection?

**Comment by dylanljones** [comment]
Hi, there is a way to export the data as JSON, but i am guessing you mean exporting the db as an unlocked SQLite database?
That is not implemented yet, but i will add it in the next release:)

**Comment by dylanljones** [comment]
You can now create a decrypted copy of the db by calling:

````python
db = Rekordbox6Database()
db.copy_unlocked("master_unlocked.db")
````

**Comment by gsuberland** [comment]
Perfect! Thanks for sorting this so quickly.
